name: pps
channels:
  - pytorch
dependencies:
  - pip
  - python
  - numpy
  - matplotlib
  - scipy
  - pytorch::pytorch 
  - torchvision
  - torchaudio
  - pandas
  - pillow
  - seaborn
  - tensorboard
  - tqdm
  - pip:
    - opacus
